Feat: Update GitHub Actions workflow to implement deployment process using SSH and environment variables

diff --git a/.github/workflows/automation.yml b/.github/workflows/automation.yml
--- a/.github/workflows/automation.yml
+++ b/.github/workflows/automation.yml
@@ -1,24 +1,40 @@
-name: "automate-all-the-things"
+name: Deploy
 
 on:
   push:
-    branches:
-      - 'main'
+    branches: [ main ]
+
+env:
+  APP_DIR: /srv/engflowbot
+  REPO_URL: git@github.com:darkweid/EngFlowBot.git
 
 jobs:
-  # Название задачи, которое будет отображаться в GitHub
-  build_and_push:
+  deploy:
     runs-on: ubuntu-latest
+
     steps:
-      -
-        name: Login to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-      -
-        name: Build and push
-        uses: docker/build-push-action@v5
-        with:
-          push: true
-          tags: darkweid/english_bot_prus:latest
+      - uses: actions/checkout@v4
+
+      - name: Set up SSH
+        run: |
+          mkdir -p ~/.ssh
+          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_deploy_eng_bot
+          chmod 600 ~/.ssh/id_deploy_eng_bot
+          ssh-keyscan -H "${{ secrets.SERVER_IP }}" >> ~/.ssh/known_hosts
+
+      - name: SSH deploy
+        run: |
+          ssh -i ~/.ssh/id_deploy_eng_bot -o StrictHostKeyChecking=no \
+            ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
+              set -e                                      # stop on error
+          
+              mkdir -p $APP_DIR
+          
+              if [ ! -d \"$APP_DIR/.git\" ]; then
+                git clone $REPO_URL $APP_DIR
+              fi
+          
+              cd $APP_DIR
+              git pull origin main
+              make run
+            "
